// ■チャートデータ各種定義
//	※このファイルは自動生成されたものです！手動での編集はご遠慮ください！
(const) %[
	"branches" => (const) [
		"s013*013_01_jump",
		"s013*013_02_jump",
		"s013*013_ama_route",
		"s013*part_013_routejump"
	],
	"captions" => (const) %[
		"s001*part_001" => (const) [
			"【CHAPTER 1-1】"
		],
		"s002*part_002" => (const) [
			"【CHAPTER 1-2】"
		],
		"s004*part_004" => (const) [
			"【CHAPTER 1-4】"
		],
		"s005*part_005" => (const) [
			"【CHAPTER 1-5】"
		],
		"s005*part_005_sel1" => (const) [
			"【天音】「じゃあ……どうしよっか？　誰の服から見に行く？」"
		],
		"s006*part_006" => (const) [
			"【CHAPTER 2-1】"
		],
		"s009*part_009" => (const) [
			"【CHAPTER 2-4】"
		],
		"s010*part_010" => (const) [
			"【CHAPTER 2-6】"
		],
		"s011*part_011" => (const) [
			"【CHAPTER 3-1】"
		],
		"s011*part_011_sel1" => (const) [
			"【かぐ耶】「それに……こう見えても嫌いじゃないのよ。家事をすることが」"
		],
		"s012*chapter3-3" => (const) [
			"【CHAPTER 3-3】"
		],
		"s012*part_012" => (const) [
			"【CHAPTER 3-2】"
		],
		"s012*part_012_sel1" => (const) [
			"【風実花】「なにかわからないことがあったら、いつでも質問しに来ていいからね」"
		],
		"s013*013_01com_jump" => (const) [
			"【CHAPTER 3-4】"
		],
		"s013*part_013" => (const) [
			"【CHAPTER 3-4】"
		],
		"s013*part_013_01com" => (const) [
			"【CHAPTER 3-4】"
		],
		"s013*part_013_02com" => (const) [
			"【CHAPTER 3-4】"
		],
		"s013*part_013_03com" => (const) [
			"【CHAPTER 3-4】"
		],
		"s013*part_013_sel1" => (const) [
			"それでも目を引く。特に俺の目を引いたのは――"
		],
		"s013*part_013_sel2" => (const) [
			"同時に、ここで意地になって雰囲気を悪くするのも申し訳ないと思うようになって、俺は……。"
		],
		"s013*part_013_sel3" => (const) [
			"【李空】「俺も探した方がいいかな……？」"
		],
		"s013*part_013_sel4" => (const) [
			"【オリエ】「では、どういう意味でしょうか？」"
		],
		"s101" => (const) [
			"CHAPTER 4",
			"【乃愛】01.ks"
		],
		"s101*part_101" => (const) [
			"【CHAPTER 4-1】"
		],
		"s102" => (const) [
			"CHAPTER 4",
			"【乃愛】02.ks"
		],
		"s102*part_102" => (const) [
			"【CHAPTER 4-2】"
		],
		"s103" => (const) [
			"CHAPTER 4",
			"【乃愛】03.ks"
		],
		"s103*part_103" => (const) [
			"【CHAPTER 4-3】"
		],
		"s104" => (const) [
			"CHAPTER 5",
			"【乃愛】04.ks"
		],
		"s104*part_104" => (const) [
			"【CHAPTER 5-1】"
		],
		"s105" => (const) [
			"CHAPTER 5",
			"【乃愛】05.ks"
		],
		"s105*part_105" => (const) [
			"【CHAPTER 5-2】"
		],
		"s106" => (const) [
			"CHAPTER 5",
			"【乃愛】06.ks"
		],
		"s106*part_106" => (const) [
			"【CHAPTER 5-3】"
		],
		"s113" => (const) [
			"CHAPTER 7",
			"【乃愛】13.ks"
		],
		"s113*part_113" => (const) [
			"【CHAPTER 7-1】"
		],
		"s114" => (const) [
			"CHAPTER 7",
			"【乃愛】14（H3）END.ks"
		],
		"s114*part_114" => (const) [
			"【CHAPTER 7-2】"
		],
		"s115" => (const) [
			"EPILOGUE",
			"【乃愛】15（EP）.ks"
		],
		"s115*part_115" => (const) [
			"【epilogue】"
		],
		"s200" => (const) [
			"CHAPTER 3",
			"【天音】00_分岐.ks"
		],
		"s200*part_200" => (const) [
			"【CHAPTER 3-4】"
		],
		"s201" => (const) [
			"CHAPTER 4",
			"【天音】01.ks"
		],
		"s201*part_201" => (const) [
			"【CHAPTER 4-1】"
		],
		"s202" => (const) [
			"CHAPTER 4",
			"【天音】02_2.ks"
		],
		"s202*part_202" => (const) [
			"【CHAPTER 4-2】"
		],
		"s203" => (const) [
			"CHAPTER 4",
			"【天音】03.ks"
		],
		"s203*part_203" => (const) [
			"【CHAPTER 4-3】"
		],
		"s205" => (const) [
			"CHAPTER 5",
			"【天音】05_2.ks"
		],
		"s205*part_205" => (const) [
			"【CHAPTER 5-1】"
		],
		"s206" => (const) [
			"CHAPTER 5",
			"【天音】06（H1）.ks"
		],
		"s206*part_206" => (const) [
			"【CHAPTER 5-2】"
		],
		"s211" => (const) [
			"CHAPTER 6",
			"【天音】11.ks"
		],
		"s211*part_211" => (const) [
			"【CHAPTER 6-3】"
		],
		"s212" => (const) [
			"CHAPTER 7",
			"【天音】12（END）.ks"
		],
		"s212*part_212" => (const) [
			"【CHAPTER 7-1】"
		],
		"s213" => (const) [
			"EPILOGUE",
			"【天音】13（EP-H4）.ks"
		],
		"s213*part_213" => (const) [
			"【epilogue】"
		],
		"s301" => (const) [
			"CHAPTER 4",
			"【来海】01.ks"
		],
		"s301*part_301" => (const) [
			"【CHAPTER 4-1】"
		],
		"s302" => (const) [
			"CHAPTER 4",
			"【来海】02.ks"
		],
		"s302*part_302" => (const) [
			"【CHAPTER 4-2】"
		],
		"s303" => (const) [
			"CHAPTER 4",
			"【来海】03.ks"
		],
		"s303*part_303" => (const) [
			"【CHAPTER 4-3】"
		],
		"s304" => (const) [
			"CHAPTER 4",
			"【来海】04.ks"
		],
		"s304*part_304" => (const) [
			"【CHAPTER 4-4】"
		],
		"s305" => (const) [
			"CHAPTER 4",
			"【来海】05.ks"
		],
		"s305*part_305" => (const) [
			"【CHAPTER 4-5】"
		],
		"s306" => (const) [
			"CHAPTER 4",
			"【来海】06.ks"
		],
		"s306*part_306" => (const) [
			"【CHAPTER 4-6】"
		],
		"s307" => (const) [
			"CHAPTER 5",
			"【来海】07.ks"
		],
		"s307*part_307" => (const) [
			"【CHAPTER 5-1】"
		],
		"s308" => (const) [
			"CHAPTER 5",
			"【来海】08.ks"
		],
		"s308*part_308" => (const) [
			"【CHAPTER 5-2】"
		],
		"s309" => (const) [
			"CHAPTER 5",
			"【来海】09.ks"
		],
		"s309*part_309" => (const) [
			"【CHAPTER 5-3】"
		],
		"s310" => (const) [
			"CHAPTER 5",
			"【来海】10.ks"
		],
		"s310*part_310" => (const) [
			"【CHAPTER 5-4】"
		],
		"s311" => (const) [
			"CHAPTER 6",
			"【来海】11.ks"
		],
		"s311*part_311" => (const) [
			"【CHAPTER 6-1】"
		],
		"s312" => (const) [
			"CHAPTER 6",
			"【来海】12.ks"
		],
		"s312*part_312" => (const) [
			"【CHAPTER 6-2】"
		],
		"s313" => (const) [
			"CHAPTER 6",
			"【来海】13.ks"
		],
		"s313*part_313" => (const) [
			"【CHAPTER 6-3】"
		],
		"s314" => (const) [
			"CHAPTER 6",
			"【来海】14.ks"
		],
		"s314*part_314" => (const) [
			"【CHAPTER 6-4】"
		],
		"s315" => (const) [
			"CHAPTER 7",
			"【来海】15.ks"
		],
		"s315*part_315" => (const) [
			"【CHAPTER 7-1】"
		],
		"s316" => (const) [
			"CHAPTER 7",
			"【来海】16.ks"
		],
		"s316*part_316" => (const) [
			"【CHAPTER 7-2】"
		],
		"s317" => (const) [
			"CHAPTER 7",
			"【来海】17.ks"
		],
		"s317*part_317" => (const) [
			"【CHAPTER 7-3】"
		],
		"s318" => (const) [
			"CHAPTER 7",
			"【来海】18.ks"
		],
		"s318*part_318" => (const) [
			"【CHAPTER 7-4】"
		],
		"s319" => (const) [
			"CHAPTER 8",
			"【来海】19.ks"
		],
		"s319*part_319" => (const) [
			"【CHAPTER 8-1】"
		],
		"s320" => (const) [
			"CHAPTER 8",
			"【来海】20.ks"
		],
		"s320*part_320" => (const) [
			"【CHAPTER 8-2】"
		],
		"s321" => (const) [
			"EPILOGUE",
			"【来海】21.ks"
		],
		"s321*part_321" => (const) [
			"【epilogue】"
		],
		"s401" => (const) [
			"CHAPTER 4",
			"【かぐ耶】01.ks"
		],
		"s401*part_401" => (const) [
			"【CHAPTER 4-1】"
		],
		"s402" => (const) [
			"CHAPTER 4",
			"【かぐ耶】02.ks"
		],
		"s402*part_402" => (const) [
			"【CHAPTER 4-2】"
		],
		"s403" => (const) [
			"CHAPTER 4",
			"【かぐ耶】03.ks"
		],
		"s403*part_403" => (const) [
			"【CHAPTER 4-3】"
		],
		"s405" => (const) [
			"CHAPTER 4",
			"【かぐ耶】05.ks"
		],
		"s405*part_405" => (const) [
			"【CHAPTER 4-6】"
		],
		"s406" => (const) [
			"CHAPTER 4",
			"【かぐ耶】06.ks"
		],
		"s406*chapter4-8_kag" => (const) [
			"【CHAPTER 4-8】"
		],
		"s406*part_406" => (const) [
			"【CHAPTER 4-7】"
		],
		"s407" => (const) [
			"CHAPTER 4",
			"【かぐ耶】07.ks"
		],
		"s407*part_407" => (const) [
			"【CHAPTER 4-9】"
		],
		"s416" => (const) [
			"CHAPTER 7",
			"【かぐ耶】16.ks"
		],
		"s416*part_416" => (const) [
			"【CHAPTER 7-1】"
		],
		"s417" => (const) [
			"CHAPTER 7",
			"【かぐ耶】17.ks"
		],
		"s417*part_417" => (const) [
			"【CHAPTER 7-2】"
		],
		"s418" => (const) [
			"CHAPTER 7",
			"【かぐ耶】18.ks"
		],
		"s418*part_418" => (const) [
			"【CHAPTER 7-3】"
		],
		"s419" => (const) [
			"EPILOGUE",
			"【かぐ耶】19.ks"
		],
		"s419*part_419" => (const) [
			"【epilogue】"
		],
		"s501" => (const) [
			"CHAPTER 4",
			"E01_4.ks"
		],
		"s501*part_501" => (const) [
			"【CHAPTER 4-1】"
		],
		"s502" => (const) [
			"CHAPTER 4",
			"E02_2.ks"
		],
		"s502*part_502" => (const) [
			"【CHAPTER 4-1】"
		],
		"s503" => (const) [
			"CHAPTER 4",
			"E03_3.ks"
		],
		"s503*part_503" => (const) [
			"【CHAPTER 4-2】"
		],
		"s504" => (const) [
			"CHAPTER 4",
			"E04H.ks"
		],
		"s504*part_504" => (const) [
			"【CHAPTER 4-3】"
		],
		"s506" => (const) [
			"CHAPTER 5",
			"E06_2.ks"
		],
		"s506*chapter5-2_ori" => (const) [
			"【CHAPTER 5-2】"
		],
		"s506*part_506" => (const) [
			"【CHAPTER 5-1】"
		],
		"s507" => (const) [
			"CHAPTER 5",
			"E07_3.ks"
		],
		"s507*chapter5-4_ori" => (const) [
			"【CHAPTER 5-4】"
		],
		"s507*part_507" => (const) [
			"【CHAPTER 5-3】"
		],
		"s508" => (const) [
			"CHAPTER 5",
			"E08_3.ks"
		],
		"s508*part_508" => (const) [
			"【CHAPTER 5-4】"
		],
		"s509" => (const) [
			"CHAPTER 6",
			"E09_2.ks"
		],
		"s509*part_509" => (const) [
			"【CHAPTER 6-1】"
		],
		"s519" => (const) [
			"CHAPTER 7",
			"E19.ks"
		],
		"s519*part_519" => (const) [
			"【CHAPTER 7-2】"
		],
		"s520" => (const) [
			"EPILOGUE",
			"E20.ks"
		],
		"s520*part_520" => (const) [
			"【epilogue】"
		],
		"s601" => (const) [
			"CHAPTER 4",
			"【風実花】01（お土産）.ks"
		],
		"s601*part_601" => (const) [
			"【CHAPTER 4-1】"
		],
		"s603" => (const) [
			"CHAPTER 4",
			"【風実花】03（水着）.ks"
		],
		"s603*part_603" => (const) [
			"【CHAPTER 4-3】"
		],
		"s604" => (const) [
			"CHAPTER 4",
			"【風実花】04（課外授業）.ks"
		],
		"s604*part_604" => (const) [
			"【CHAPTER 4-4】"
		],
		"s606" => (const) [
			"CHAPTER 5",
			"【風実花】06（しつこい男）.ks"
		],
		"s606*part_606" => (const) [
			"【CHAPTER 5-3】"
		],
		"s607" => (const) [
			"EPILOGUE",
			"【風実花】07（END）.ks"
		],
		"s607*part_607" => (const) [
			"【epilogue】"
		]
	],
	"chain" => (const) %[
		"s001*part_001" => "s002*part_002",
		"s002*part_002" => "s004*part_004",
		"s004*part_004" => "s005*part_005",
		"s005*part_005" => "s005*part_005_sel1",
		"s005*part_005_01A" => "s005*part_005_01com",
		"s005*part_005_01B" => "s005*part_005_01com",
		"s005*part_005_01C" => "s005*part_005_01com",
		"s005*part_005_01com" => "s006*part_006",
		"s005*part_005_sel1" => (const) [
			"s005*part_005_01A",
			"s005*part_005_01B",
			"s005*part_005_01C"
		],
		"s005*part_005_sel1:s005*part_005_01A" => (const) [
			"select",
			1
		],
		"s005*part_005_sel1:s005*part_005_01B" => (const) [
			"select",
			2
		],
		"s005*part_005_sel1:s005*part_005_01C" => (const) [
			"select",
			3
		],
		"s006*part_006" => "s009*part_009",
		"s009*part_009" => "s010*part_010",
		"s010*part_010" => "s011*part_011",
		"s011*part_011" => "s011*part_011_sel1",
		"s011*part_011_01A" => "s012*part_012",
		"s011*part_011_01B" => "s012*part_012",
		"s011*part_011_sel1" => (const) [
			"s011*part_011_01A",
			"s011*part_011_01B"
		],
		"s011*part_011_sel1:s011*part_011_01A" => (const) [
			"select",
			1
		],
		"s011*part_011_sel1:s011*part_011_01B" => (const) [
			"select",
			2
		],
		"s012*chapter3-3" => "s013*part_013",
		"s012*part_012" => "s012*part_012_sel1",
		"s012*part_012_01A" => "s012*chapter3-3",
		"s012*part_012_01B" => "s012*chapter3-3",
		"s012*part_012_sel1" => (const) [
			"s012*part_012_01A",
			"s012*part_012_01B"
		],
		"s012*part_012_sel1:s012*part_012_01A" => (const) [
			"select",
			1
		],
		"s012*part_012_sel1:s012*part_012_01B" => (const) [
			"select",
			2
		],
		"s013*013_01A_jump" => "s013*013_01com_jump",
		"s013*013_01_jump" => (const) [
			"s013*013_01A_jump",
			"s600*part_600",
			"s013*013_01com_jump"
		],
		"s013*013_01_jump:s013*013_01A_jump" => (const) [
			"branch",
			"ama == 1"
		],
		"s013*013_01_jump:s013*013_01com_jump" => (const) [
			"branch",
			void
		],
		"s013*013_01_jump:s600*part_600" => (const) [
			"branch",
			"fum == 2"
		],
		"s013*013_01com_jump" => "s013*013_02_jump",
		"s013*013_02_jump" => (const) [
			"s100*part_100",
			"s013*013_02com_jump"
		],
		"s013*013_02_jump:s013*013_02com_jump" => (const) [
			"branch",
			void
		],
		"s013*013_02_jump:s100*part_100" => (const) [
			"branch",
			"noa == 1"
		],
		"s013*013_02com_jump" => "s013*part_013_sel3",
		"s013*013_04com" => "s013*part_013_routejump",
		"s013*013_ama_route" => (const) [
			"s013*route_jump_ama",
			"s013*013_04com"
		],
		"s013*013_ama_route:s013*013_04com" => (const) [
			"branch",
			void
		],
		"s013*013_ama_route:s013*route_jump_ama" => (const) [
			"branch",
			"ama == 1"
		],
		"s013*part_013" => "s013*part_013_sel1",
		"s013*part_013_01A" => "s013*part_013_01com",
		"s013*part_013_01B" => "s013*part_013_01com",
		"s013*part_013_01C" => "s013*part_013_01com",
		"s013*part_013_01D" => "s013*part_013_01com",
		"s013*part_013_01E" => "s013*part_013_01com",
		"s013*part_013_01com" => "s013*part_013_sel2",
		"s013*part_013_02A" => "s013*part_013_02com",
		"s013*part_013_02B" => "s013*part_013_02com",
		"s013*part_013_02com" => "s013*013_01_jump",
		"s013*part_013_03A" => "s013*part_013_03com",
		"s013*part_013_03B" => "s013*part_013_03com",
		"s013*part_013_03C" => "s013*part_013_sel4",
		"s013*part_013_03com" => "s013*013_ama_route",
		"s013*part_013_04A" => "s013*part_013_03com",
		"s013*part_013_04B" => "s013*part_013_03com",
		"s013*part_013_routejump" => (const) [
			"s013*route_jump_noa",
			"s013*route_jump_kur",
			"s013*route_jump_kag",
			"s013*route_jump_ori",
			"s013*route_jump_fum",
			"s013*normal_end"
		],
		"s013*part_013_routejump:s013*normal_end" => (const) [
			"branch",
			void
		],
		"s013*part_013_routejump:s013*route_jump_fum" => (const) [
			"branch",
			"fum == 2 && .checkAnyClear"
		],
		"s013*part_013_routejump:s013*route_jump_kag" => (const) [
			"branch",
			"kag == 2"
		],
		"s013*part_013_routejump:s013*route_jump_kur" => (const) [
			"branch",
			"kur == 2"
		],
		"s013*part_013_routejump:s013*route_jump_noa" => (const) [
			"branch",
			"noa == 1"
		],
		"s013*part_013_routejump:s013*route_jump_ori" => (const) [
			"branch",
			"ori == 2 && .checkAnyClear"
		],
		"s013*part_013_sel1" => (const) [
			"s013*part_013_01A",
			"s013*part_013_01C",
			"s013*part_013_01D",
			"s013*part_013_01E",
			"s013*part_013_01B"
		],
		"s013*part_013_sel1:s013*part_013_01A" => (const) [
			"select",
			1
		],
		"s013*part_013_sel1:s013*part_013_01B" => (const) [
			"select",
			5
		],
		"s013*part_013_sel1:s013*part_013_01C" => (const) [
			"select",
			2
		],
		"s013*part_013_sel1:s013*part_013_01D" => (const) [
			"select",
			3
		],
		"s013*part_013_sel1:s013*part_013_01E" => (const) [
			"select",
			4
		],
		"s013*part_013_sel2" => (const) [
			"s013*part_013_02A",
			"s013*part_013_02B"
		],
		"s013*part_013_sel2:s013*part_013_02A" => (const) [
			"select",
			1
		],
		"s013*part_013_sel2:s013*part_013_02B" => (const) [
			"select",
			2
		],
		"s013*part_013_sel3" => (const) [
			"s013*part_013_03A",
			"s013*part_013_03B",
			"s013*part_013_03C"
		],
		"s013*part_013_sel3:s013*part_013_03A" => (const) [
			"select",
			1
		],
		"s013*part_013_sel3:s013*part_013_03B" => (const) [
			"select",
			2
		],
		"s013*part_013_sel3:s013*part_013_03C" => (const) [
			"select",
			3
		],
		"s013*part_013_sel4" => (const) [
			"s013*part_013_04A",
			"s013*part_013_04B"
		],
		"s013*part_013_sel4:s013*part_013_04A" => (const) [
			"select",
			1
		],
		"s013*part_013_sel4:s013*part_013_04B" => (const) [
			"select",
			2
		],
		"s100*part_100" => "s013*part_013_03com",
		"s101*chapter_noaH2_after" => "s102*part_102",
		"s101*part_101" => "s101*chapter_noaH2_after",
		"s102*part_102" => "s103*part_103",
		"s103*part_103" => "s104*part_104",
		"s104*part_104" => "s105*part_105",
		"s105*part_105" => "s106*part_106",
		"s106*part_106" => "s113*part_113",
		"s113*part_113" => "s114*part_114",
		"s114*part_114" => "s115*part_115",
		"s200*part_200" => "s201*part_201",
		"s201*part_201" => "s202*part_202",
		"s202*part_202" => "s203*part_203",
		"s203*part_203" => "s205*part_205",
		"s205*part_205" => "s206*part_206",
		"s206*part_206" => "s211*part_211",
		"s211*part_211" => "s212*part_212",
		"s212*part_212" => "s213*part_213",
		"s301*part_301" => "s302*part_302",
		"s302*part_302" => "s303*part_303",
		"s303*part_303" => "s304*part_304",
		"s304*part_304" => "s305*part_305",
		"s305*part_305" => "s306*part_306",
		"s306*part_306" => "s307*part_307",
		"s307*part_307" => "s308*part_308",
		"s308*part_308" => "s309*part_309",
		"s309*part_309" => "s310*part_310",
		"s310*part_310" => "s311*part_311",
		"s311*part_311" => "s312*part_312",
		"s312*part_312" => "s313*part_313",
		"s313*part_313" => "s314*part_314",
		"s314*part_314" => "s315*part_315",
		"s315*part_315" => "s316*part_316",
		"s316*part_316" => "s317*part_317",
		"s317*part_317" => "s318*part_318",
		"s318*part_318" => "s319*part_319",
		"s319*part_319" => "s320*part_320",
		"s320*chapter_kurH4_after" => "s321*part_321",
		"s320*part_320" => "s320*chapter_kurH4_after",
		"s401*part_401" => "s402*part_402",
		"s402*part_402" => "s403*part_403",
		"s403*part_403" => "s405*part_405",
		"s405*part_405" => "s406*part_406",
		"s406*chapter4-8_kag" => "s407*part_407",
		"s406*part_406" => "s406*chapter4-8_kag",
		"s407*part_407" => "s416*part_416",
		"s416*part_416" => "s417*part_417",
		"s417*part_417" => "s418*part_418",
		"s418*part_418" => "s419*part_419",
		"s501*part_501" => "s502*part_502",
		"s502*part_502" => "s503*part_503",
		"s503*part_503" => "s504*part_504",
		"s504*part_504" => "s506*part_506",
		"s506*chapter5-2_ori" => "s507*part_507",
		"s506*part_506" => "s506*chapter5-2_ori",
		"s507*chapter5-4_ori" => "s508*part_508",
		"s507*part_507" => "s507*chapter5-4_ori",
		"s508*part_508" => "s509*part_509",
		"s509*part_509" => "s519*part_519",
		"s519*part_519" => "s520*part_520",
		"s600*part_600" => "s013*013_01com_jump",
		"s601*part_601" => "s603*part_603",
		"s603*part_603" => "s604*part_604",
		"s604*part_604" => "s606*part_606",
		"s606*part_606" => "s607*part_607"
	],
	"flagkeys" => (const) [
		"ama",
		"fum",
		"kag",
		"kur",
		"noa",
		"ori",
		"sel05_flag",
		"sel11_flag",
		"sel12_flag",
		"sel13_2_flag",
		"sel13_3_flag",
		"sel13_4_flag",
		"sel13_flag"
	],
	"flags" => (const) %[
		"ama" => (const) [
			(const) [
				"s011*part_011_sel1",
				2,
				1
			],
			(const) [
				"s013*part_013_sel2",
				2,
				1
			]
		],
		"fum" => (const) [
			(const) [
				"s005*part_005_sel1",
				3,
				1
			],
			(const) [
				"s012*part_012_sel1",
				1,
				1
			]
		],
		"kag" => (const) [
			(const) [
				"s011*part_011_sel1",
				1,
				1
			],
			(const) [
				"s013*part_013_sel3",
				1,
				1
			]
		],
		"kur" => (const) [
			(const) [
				"s013*part_013_sel2",
				1,
				1
			],
			(const) [
				"s013*part_013_sel3",
				2,
				1
			]
		],
		"noa" => (const) [
			(const) [
				"s005*part_005_sel1",
				1,
				1
			]
		],
		"ori" => (const) [
			(const) [
				"s013*part_013_sel3",
				3,
				1
			],
			(const) [
				"s013*part_013_sel4",
				1,
				1
			]
		],
		"sel05_flag" => (const) [
			(const) [
				"s005*part_005_sel1",
				1,
				1
			],
			(const) [
				"s005*part_005_sel1",
				2,
				0
			],
			(const) [
				"s005*part_005_sel1",
				3,
				2
			]
		],
		"sel11_flag" => (const) [
			(const) [
				"s011*part_011_sel1",
				1,
				0
			],
			(const) [
				"s011*part_011_sel1",
				2,
				1
			]
		],
		"sel12_flag" => (const) [
			(const) [
				"s012*part_012_sel1",
				1,
				0
			],
			(const) [
				"s012*part_012_sel1",
				2,
				1
			]
		],
		"sel13_2_flag" => (const) [
			(const) [
				"s013*part_013_sel2",
				1,
				0
			],
			(const) [
				"s013*part_013_sel2",
				2,
				1
			]
		],
		"sel13_3_flag" => (const) [
			(const) [
				"s013*part_013_sel3",
				1,
				0
			],
			(const) [
				"s013*part_013_sel3",
				2,
				1
			],
			(const) [
				"s013*part_013_sel3",
				3,
				2
			]
		],
		"sel13_4_flag" => (const) [
			(const) [
				"s013*part_013_sel4",
				1,
				0
			],
			(const) [
				"s013*part_013_sel4",
				2,
				1
			]
		],
		"sel13_flag" => (const) [
			(const) [
				"s013*part_013_sel1",
				1,
				0
			],
			(const) [
				"s013*part_013_sel1",
				2,
				1
			],
			(const) [
				"s013*part_013_sel1",
				3,
				2
			],
			(const) [
				"s013*part_013_sel1",
				4,
				3
			],
			(const) [
				"s013*part_013_sel1",
				5,
				4
			]
		]
	],
	"items" => (const) [
		(const) [
			(const) %[
				"id" => "chapter_1_1",
				"name" => "CHAPTER 1",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "いつも通り？",
				"id" => "s001*part_001",
				"storage" => "【共通】01.ks",
				"tag" => "s001",
				"target" => "*part_001",
				"type" => "section"
			],
			(const) %[
				"comment" => "天使降臨",
				"id" => "s002*part_002",
				"storage" => "【共通】02.ks",
				"tag" => "s002",
				"target" => "*part_002",
				"type" => "section"
			],
			(const) %[
				"comment" => "来訪者たち",
				"id" => "s004*part_004",
				"preofs" => 50,
				"storage" => "【共通】04.ks",
				"tag" => "s004",
				"target" => "*part_004",
				"type" => "section"
			],
			(const) %[
				"comment" => "お買い物",
				"id" => "s005*part_005",
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005",
				"type" => "section"
			],
			(const) %[
				"comment" => "誰の服から？",
				"id" => "s005*part_005_sel1",
				"selects" => (const) [
					"乃愛から",
					1,
					"シュトリアさんから",
					2,
					"とりあえず休憩",
					3
				],
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005_sel1",
				"type" => "select"
			],
			(const) %[
				"comment" => "乃愛",
				"id" => "s005*part_005_01A",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005_01A",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "シュトリアさん",
				"id" => "s005*part_005_01B",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005_01B",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "休憩",
				"id" => "s005*part_005_01C",
				"shape" => "subsection",
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005_01C",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 3,
				"vnumer" => 2
			],
			(const) %[
				"comment" => "今日の夕食は？",
				"id" => "s005*part_005_01com",
				"preofs" => 50,
				"storage" => "【共通】05.ks",
				"tag" => "s005",
				"target" => "*part_005_01com",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_1_2",
				"name" => "CHAPTER 2",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "乃愛との暮らし",
				"id" => "s006*part_006",
				"storage" => "【共通】06.ks",
				"tag" => "s006",
				"target" => "*part_006",
				"type" => "section"
			],
			(const) %[
				"comment" => "特訓は続くよ",
				"id" => "s009*part_009",
				"preofs" => 50,
				"storage" => "【共通】09.ks",
				"tag" => "s009",
				"target" => "*part_009",
				"type" => "section"
			],
			(const) %[
				"comment" => "襲撃",
				"id" => "s010*part_010",
				"storage" => "【共通】10.ks",
				"tag" => "s010",
				"target" => "*part_010",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_1_3",
				"name" => "CHAPTER 3",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "二日酔い？",
				"id" => "s011*part_011",
				"storage" => "【共通】11.ks",
				"tag" => "s011",
				"target" => "*part_011",
				"type" => "section"
			],
			(const) %[
				"comment" => "天音の雑炊を…",
				"id" => "s011*part_011_sel1",
				"selects" => (const) [
					"お願いする",
					1,
					"やっぱり俺が",
					2
				],
				"storage" => "【共通】11.ks",
				"tag" => "s011",
				"target" => "*part_011_sel1",
				"type" => "select"
			],
			(const) %[
				"comment" => "かぐ耶にお願い",
				"id" => "s011*part_011_01A",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】11.ks",
				"tag" => "s011",
				"target" => "*part_011_01A",
				"type" => "section",
				"vdenom" => 2,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "俺が作る",
				"id" => "s011*part_011_01B",
				"shape" => "subsection",
				"storage" => "【共通】11.ks",
				"tag" => "s011",
				"target" => "*part_011_01B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 2,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "夢か現か？",
				"id" => "s012*part_012",
				"preofs" => 50,
				"storage" => "【共通】12.ks",
				"tag" => "s012",
				"target" => "*part_012",
				"type" => "section"
			],
			(const) %[
				"comment" => "風実花さんに…",
				"id" => "s012*part_012_sel1",
				"selects" => (const) [
					"なら……質問に行く",
					1,
					"特に……ないな",
					2
				],
				"storage" => "【共通】12.ks",
				"tag" => "s012",
				"target" => "*part_012_sel1",
				"type" => "select"
			],
			(const) %[
				"comment" => "質問をしに行く",
				"id" => "s012*part_012_01A",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】12.ks",
				"tag" => "s012",
				"target" => "*part_012_01A",
				"type" => "section",
				"vdenom" => 2,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "いつも通りに過ごす",
				"id" => "s012*part_012_01B",
				"shape" => "subsection",
				"storage" => "【共通】12.ks",
				"tag" => "s012",
				"target" => "*part_012_01B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 2,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "水着を買いに！",
				"id" => "s012*chapter3-3",
				"preofs" => 50,
				"storage" => "【共通】12.ks",
				"tag" => "s012",
				"target" => "*chapter3-3",
				"type" => "section"
			],
			(const) %[
				"comment" => "夏だ！　海だ！",
				"id" => "s013*part_013",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013",
				"type" => "section"
			],
			(const) %[
				"comment" => "誰の水着が…",
				"id" => "s013*part_013_sel1",
				"selects" => (const) [
					"乃愛",
					1,
					"小雲雀さん",
					2,
					"かぐ耶",
					3,
					"オリエ",
					4,
					"……天音？",
					5
				],
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_sel1",
				"type" => "select"
			],
			(const) %[
				"comment" => "乃愛の水着",
				"id" => "s013*part_013_01A",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01A",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "小雲雀さんの水着",
				"id" => "s013*part_013_01C",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01C",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "かぐ耶の水着",
				"id" => "s013*part_013_01D",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01D",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 2
			],
			(const) %[
				"comment" => "オリエの水着",
				"id" => "s013*part_013_01E",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01E",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 3
			],
			(const) %[
				"comment" => "天音の水着",
				"id" => "s013*part_013_01B",
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 5,
				"vnumer" => 4
			],
			(const) %[
				"comment" => "海の続き",
				"id" => "s013*part_013_01com",
				"preofs" => 50,
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_01com",
				"type" => "section"
			],
			(const) %[
				"comment" => "褒めるのは…",
				"id" => "s013*part_013_sel2",
				"selects" => (const) [
					"よく似合ってると思うと褒める",
					1,
					"気になっていることを尋ねる",
					2
				],
				"selevals" => (const) %[
					"2" => "sel06_flag == 1"
				],
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_sel2",
				"type" => "select"
			],
			(const) %[
				"comment" => "来海を褒める",
				"id" => "s013*part_013_02A",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_02A",
				"type" => "section",
				"vdenom" => 2,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "天音に尋ねる",
				"id" => "s013*part_013_02B",
				"shape" => "subsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_02B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 2,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "海、その後",
				"id" => "s013*part_013_02com",
				"preofs" => 50,
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_02com",
				"type" => "section"
			],
			(const) %[
				"id" => "s013*013_01_jump",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_01_jump",
				"type" => "branch"
			],
			(const) %[
				"comment" => "いい匂い？",
				"id" => "s013*013_01A_jump",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_01A_jump",
				"type" => "section",
				"vdenom" => 2,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "お土産に？",
				"id" => "s600*part_600",
				"shape" => "subsection",
				"storage" => "【風実花】00_分岐.ks",
				"tag" => "s600",
				"target" => "*part_600",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 2,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "砂浜から見る光景",
				"id" => "s013*013_01com_jump",
				"preofs" => 50,
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_01com_jump",
				"type" => "section"
			],
			(const) %[
				"id" => "s013*013_02_jump",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_02_jump",
				"type" => "branch"
			],
			(const) %[
				"comment" => "乃愛との時間",
				"id" => "s100*part_100",
				"longpass" => "-100",
				"nocr" => 1,
				"shape" => "subsection",
				"storage" => "【乃愛】00_分岐.ks",
				"tag" => "s100",
				"target" => "*part_100",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "オリエの行方",
				"id" => "s013*013_02com_jump",
				"shape" => "subsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_02com_jump",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 3,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "オリエを追って…",
				"id" => "s013*part_013_sel3",
				"selects" => (const) [
					"一緒に行く",
					1,
					"このまま荷物番を",
					2,
					"俺も探してみる",
					3
				],
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_sel3",
				"type" => "select"
			],
			(const) %[
				"comment" => "オリエを探す",
				"id" => "s013*part_013_03C",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_03C",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "かぐ耶と一緒",
				"id" => "s013*part_013_03A",
				"longpass" => "-100",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_03A",
				"type" => "section",
				"vdenom" => 5,
				"vnumer" => 3
			],
			(const) %[
				"comment" => "荷物番",
				"id" => "s013*part_013_03B",
				"longpass" => "-100",
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_03B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 5,
				"vnumer" => 4
			],
			(const) %[
				"comment" => "オリエの水着",
				"id" => "s013*part_013_sel4",
				"selects" => (const) [
					"言ってみる",
					1,
					"言わないまま",
					2
				],
				"storage" => "【共通】13.ks",
				"syncvert" => "s013*part_013_03C",
				"tag" => "s013",
				"target" => "*part_013_sel4",
				"type" => "select"
			],
			(const) %[
				"comment" => "褒めてみる",
				"id" => "s013*part_013_04A",
				"longpass" => "-100",
				"nocr" => 1,
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_04A",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "止めておく",
				"id" => "s013*part_013_04B",
				"longpass" => "-100",
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_04B",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 3,
				"vnumer" => 1
			],
			(const) %[
				"comment" => "遊び終えて",
				"id" => "s013*part_013_03com",
				"preofs" => 50,
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_03com",
				"type" => "section"
			],
			(const) %[
				"id" => "s013*013_ama_route",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_ama_route",
				"type" => "branch"
			],
			(const) %[
				"id" => "s013*route_jump_ama",
				"nocr" => 1,
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_ama",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 0
			],
			(const) %[
				"comment" => "帰宅",
				"flowjump" => "*flowjump",
				"id" => "s013*013_04com",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*013_04com",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 3,
				"vnumer" => 1
			],
			(const) %[
				"fromid" => "s013*route_jump_ama",
				"id" => "warp_1_1",
				"route" => "天音",
				"syncpos" => "s013*route_jump_ama",
				"syncvert" => "s013*route_jump_ama",
				"type" => "warp"
			],
			(const) %[
				"id" => "s013*part_013_routejump",
				"preofs" => 70,
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*part_013_routejump",
				"type" => "branch"
			],
			(const) %[
				"comment" => "ノーマルED ",
				"id" => "s013*normal_end",
				"shape" => "minsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*normal_end",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 6,
				"vnumer" => 5
			],
			(const) %[
				"id" => "s013*route_jump_noa",
				"nocr" => 1,
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_noa",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 0
			],
			(const) %[
				"id" => "s013*route_jump_kag",
				"nocr" => 1,
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_kag",
				"type" => "section",
				"vdenom" => 3,
				"vnumer" => 1
			],
			(const) %[
				"id" => "s013*route_jump_fum",
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_fum",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 3,
				"vnumer" => 2
			],
			(const) %[
				"id" => "s013*route_jump_kur",
				"nocr" => 1,
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_kur",
				"type" => "section",
				"vdenom" => 2,
				"vnumer" => 0
			],
			(const) %[
				"id" => "s013*route_jump_ori",
				"shape" => "nonsection",
				"storage" => "【共通】13.ks",
				"tag" => "s013",
				"target" => "*route_jump_ori",
				"type" => "section",
				"vclose" => 1,
				"vdenom" => 2,
				"vnumer" => 1
			],
			(const) %[
				"fromid" => "s013*route_jump_noa",
				"id" => "warp_1_2",
				"route" => "乃愛",
				"syncpos" => "s013*route_jump_noa",
				"syncvert" => "s013*route_jump_noa",
				"type" => "warp"
			],
			(const) %[
				"fromid" => "s013*route_jump_kur",
				"id" => "warp_1_3",
				"route" => "来海",
				"syncpos" => "s013*route_jump_kur",
				"syncvert" => "s013*route_jump_kur",
				"type" => "warp"
			],
			(const) %[
				"fromid" => "s013*route_jump_kag",
				"id" => "warp_1_4",
				"route" => "かぐ耶",
				"syncpos" => "s013*route_jump_kag",
				"syncvert" => "s013*route_jump_kag",
				"type" => "warp"
			],
			(const) %[
				"fromid" => "s013*route_jump_ori",
				"id" => "warp_1_5",
				"route" => "オリエ",
				"syncpos" => "s013*route_jump_ori",
				"syncvert" => "s013*route_jump_ori",
				"type" => "warp"
			],
			(const) %[
				"fromid" => "s013*route_jump_fum",
				"id" => "warp_1_6",
				"route" => "風実花",
				"syncpos" => "s013*route_jump_fum",
				"syncvert" => "s013*route_jump_fum",
				"type" => "warp"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_2_1",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "夏が始まる",
				"id" => "s101*part_101",
				"storage" => "【乃愛】01.ks",
				"tag" => "s101",
				"target" => "*part_101",
				"type" => "section"
			],
			(const) %[
				"comment" => "気まずさ…",
				"flowjump" => "*flowjump",
				"id" => "s101*chapter_noaH2_after",
				"storage" => "【乃愛】01.ks",
				"tag" => "s101",
				"target" => "*chapter_noaH2_after",
				"type" => "section"
			],
			(const) %[
				"comment" => "夢",
				"id" => "s102*part_102",
				"storage" => "【乃愛】02.ks",
				"tag" => "s102",
				"target" => "*part_102",
				"type" => "section"
			],
			(const) %[
				"comment" => "天使の前は",
				"id" => "s103*part_103",
				"storage" => "【乃愛】03.ks",
				"tag" => "s103",
				"target" => "*part_103",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_2_2",
				"name" => "CHAPTER 5",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "気分転換",
				"id" => "s104*part_104",
				"storage" => "【乃愛】04.ks",
				"tag" => "s104",
				"target" => "*part_104",
				"type" => "section"
			],
			(const) %[
				"comment" => "守ったもの",
				"id" => "s105*part_105",
				"storage" => "【乃愛】05.ks",
				"tag" => "s105",
				"target" => "*part_105",
				"type" => "section"
			],
			(const) %[
				"comment" => "残る問題は…",
				"id" => "s106*part_106",
				"storage" => "【乃愛】06.ks",
				"tag" => "s106",
				"target" => "*part_106",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_2_3",
				"name" => "CHAPTER 7",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "因縁",
				"id" => "s113*part_113",
				"storage" => "【乃愛】13.ks",
				"tag" => "s113",
				"target" => "*part_113",
				"type" => "section"
			],
			(const) %[
				"comment" => "過去との決別",
				"id" => "s114*part_114",
				"storage" => "【乃愛】14（H3）END.ks",
				"tag" => "s114",
				"target" => "*part_114",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_2_4",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s115*part_115",
				"storage" => "【乃愛】15（EP）.ks",
				"tag" => "s115",
				"target" => "*part_115",
				"type" => "section"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_3_1",
				"name" => "CHAPTER 3",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "いい匂い？",
				"id" => "s200*part_200",
				"storage" => "【天音】00_分岐.ks",
				"tag" => "s200",
				"target" => "*part_200",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_3_2",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "天音の前世返り",
				"id" => "s201*part_201",
				"storage" => "【天音】01.ks",
				"tag" => "s201",
				"target" => "*part_201",
				"type" => "section"
			],
			(const) %[
				"comment" => "同調",
				"id" => "s202*part_202",
				"storage" => "【天音】02_2.ks",
				"tag" => "s202",
				"target" => "*part_202",
				"type" => "section"
			],
			(const) %[
				"comment" => "一緒のベッドで…",
				"id" => "s203*part_203",
				"storage" => "【天音】03.ks",
				"tag" => "s203",
				"target" => "*part_203",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_3_3",
				"name" => "CHAPTER 5",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "天音？",
				"id" => "s205*part_205",
				"storage" => "【天音】05_2.ks",
				"tag" => "s205",
				"target" => "*part_205",
				"type" => "section"
			],
			(const) %[
				"comment" => "風実花の手伝い",
				"id" => "s206*part_206",
				"storage" => "【天音】06（H1）.ks",
				"tag" => "s206",
				"target" => "*part_206",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_3_4",
				"name" => "CHAPTER 6",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "彼女の勇気",
				"id" => "s211*part_211",
				"storage" => "【天音】11.ks",
				"tag" => "s211",
				"target" => "*part_211",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_3_5",
				"name" => "CHAPTER 7",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "その後の顛末",
				"id" => "s212*part_212",
				"storage" => "【天音】12（END）.ks",
				"tag" => "s212",
				"target" => "*part_212",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_3_6",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s213*part_213",
				"storage" => "【天音】13（EP-H4）.ks",
				"tag" => "s213",
				"target" => "*part_213",
				"type" => "section"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_4_1",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "来海からの相談",
				"id" => "s301*part_301",
				"storage" => "【来海】01.ks",
				"tag" => "s301",
				"target" => "*part_301",
				"type" => "section"
			],
			(const) %[
				"comment" => "天才？",
				"id" => "s302*part_302",
				"storage" => "【来海】02.ks",
				"tag" => "s302",
				"target" => "*part_302",
				"type" => "section"
			],
			(const) %[
				"comment" => "制御できるかな？",
				"id" => "s303*part_303",
				"storage" => "【来海】03.ks",
				"tag" => "s303",
				"target" => "*part_303",
				"type" => "section"
			],
			(const) %[
				"comment" => "レッスン中",
				"id" => "s304*part_304",
				"storage" => "【来海】04.ks",
				"tag" => "s304",
				"target" => "*part_304",
				"type" => "section"
			],
			(const) %[
				"comment" => "ばったり遭遇",
				"id" => "s305*part_305",
				"storage" => "【来海】05.ks",
				"tag" => "s305",
				"target" => "*part_305",
				"type" => "section"
			],
			(const) %[
				"comment" => "デート？　相談？",
				"id" => "s306*part_306",
				"storage" => "【来海】06.ks",
				"tag" => "s306",
				"target" => "*part_306",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_4_2",
				"name" => "CHAPTER 5",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "恋人（仮）",
				"id" => "s307*part_307",
				"storage" => "【来海】07.ks",
				"tag" => "s307",
				"target" => "*part_307",
				"type" => "section"
			],
			(const) %[
				"comment" => "クルミとリックン",
				"id" => "s308*part_308",
				"storage" => "【来海】08.ks",
				"tag" => "s308",
				"target" => "*part_308",
				"type" => "section"
			],
			(const) %[
				"comment" => "彼女の不安",
				"id" => "s309*part_309",
				"storage" => "【来海】09.ks",
				"tag" => "s309",
				"target" => "*part_309",
				"type" => "section"
			],
			(const) %[
				"comment" => "試してみる？",
				"id" => "s310*part_310",
				"storage" => "【来海】10.ks",
				"tag" => "s310",
				"target" => "*part_310",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_4_3",
				"name" => "CHAPTER 6",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "それぞれの夏休み",
				"id" => "s311*part_311",
				"storage" => "【来海】11.ks",
				"tag" => "s311",
				"target" => "*part_311",
				"type" => "section"
			],
			(const) %[
				"comment" => "プレゼント",
				"id" => "s312*part_312",
				"storage" => "【来海】12.ks",
				"tag" => "s312",
				"target" => "*part_312",
				"type" => "section"
			],
			(const) %[
				"comment" => "不運にもほどがある",
				"id" => "s313*part_313",
				"storage" => "【来海】13.ks",
				"tag" => "s313",
				"target" => "*part_313",
				"type" => "section"
			],
			(const) %[
				"comment" => "呪われた李空",
				"id" => "s314*part_314",
				"storage" => "【来海】14.ks",
				"tag" => "s314",
				"target" => "*part_314",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_4_4",
				"name" => "CHAPTER 7",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "刺客を探せ！",
				"id" => "s315*part_315",
				"storage" => "【来海】15.ks",
				"tag" => "s315",
				"target" => "*part_315",
				"type" => "section"
			],
			(const) %[
				"comment" => "宵の監視者",
				"id" => "s316*part_316",
				"storage" => "【来海】16.ks",
				"tag" => "s316",
				"target" => "*part_316",
				"type" => "section"
			],
			(const) %[
				"comment" => "彼の選択",
				"id" => "s317*part_317",
				"storage" => "【来海】17.ks",
				"tag" => "s317",
				"target" => "*part_317",
				"type" => "section"
			],
			(const) %[
				"comment" => "ヴェガと届ける言葉",
				"id" => "s318*part_318",
				"storage" => "【来海】18.ks",
				"tag" => "s318",
				"target" => "*part_318",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_4_5",
				"name" => "CHAPTER 8",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "夏休みの過ごし方",
				"id" => "s319*part_319",
				"storage" => "【来海】19.ks",
				"tag" => "s319",
				"target" => "*part_319",
				"type" => "section"
			],
			(const) %[
				"comment" => "約束の海",
				"id" => "s320*part_320",
				"storage" => "【来海】20.ks",
				"tag" => "s320",
				"target" => "*part_320",
				"type" => "section"
			],
			(const) %[
				"comment" => "（仮）じゃなくて",
				"id" => "s320*chapter_kurH4_after",
				"storage" => "【来海】20.ks",
				"tag" => "s320",
				"target" => "*chapter_kurH4_after",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_4_6",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s321*part_321",
				"storage" => "【来海】21.ks",
				"tag" => "s321",
				"target" => "*part_321",
				"type" => "section"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_5_1",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "詰められる距離感",
				"id" => "s401*part_401",
				"storage" => "【かぐ耶】01.ks",
				"tag" => "s401",
				"target" => "*part_401",
				"type" => "section"
			],
			(const) %[
				"comment" => "とにもかくにも終業式",
				"id" => "s402*part_402",
				"storage" => "【かぐ耶】02.ks",
				"tag" => "s402",
				"target" => "*part_402",
				"type" => "section"
			],
			(const) %[
				"comment" => "二人だけの秘密の特訓",
				"id" => "s403*part_403",
				"storage" => "【かぐ耶】03.ks",
				"tag" => "s403",
				"target" => "*part_403",
				"type" => "section"
			],
			(const) %[
				"comment" => "これはもう恋だった",
				"id" => "s405*part_405",
				"storage" => "【かぐ耶】05.ks",
				"tag" => "s405",
				"target" => "*part_405",
				"type" => "section"
			],
			(const) %[
				"comment" => "俺の魔法",
				"id" => "s406*part_406",
				"storage" => "【かぐ耶】06.ks",
				"tag" => "s406",
				"target" => "*part_406",
				"type" => "section"
			],
			(const) %[
				"comment" => "マジックジャマー",
				"id" => "s406*chapter4-8_kag",
				"storage" => "【かぐ耶】06.ks",
				"tag" => "s406",
				"target" => "*chapter4-8_kag",
				"type" => "section"
			],
			(const) %[
				"comment" => "結ばれる“特別”",
				"id" => "s407*part_407",
				"storage" => "【かぐ耶】07.ks",
				"tag" => "s407",
				"target" => "*part_407",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_5_2",
				"name" => "CHAPTER 7",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "女王の座",
				"id" => "s416*part_416",
				"storage" => "【かぐ耶】16.ks",
				"tag" => "s416",
				"target" => "*part_416",
				"type" => "section"
			],
			(const) %[
				"comment" => "永遠すら信じられるほど",
				"id" => "s417*part_417",
				"storage" => "【かぐ耶】17.ks",
				"tag" => "s417",
				"target" => "*part_417",
				"type" => "section"
			],
			(const) %[
				"comment" => "未来へのお見送り",
				"id" => "s418*part_418",
				"storage" => "【かぐ耶】18.ks",
				"tag" => "s418",
				"target" => "*part_418",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_5_3",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s419*part_419",
				"storage" => "【かぐ耶】19.ks",
				"tag" => "s419",
				"target" => "*part_419",
				"type" => "section"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_6_1",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "待望の夏休み",
				"id" => "s501*part_501",
				"storage" => "E01_4.ks",
				"tag" => "s501",
				"target" => "*part_501",
				"type" => "section"
			],
			(const) %[
				"comment" => "みんなで遊ぼう",
				"id" => "s502*part_502",
				"storage" => "E02_2.ks",
				"tag" => "s502",
				"target" => "*part_502",
				"type" => "section"
			],
			(const) %[
				"comment" => "協力体制の確立",
				"id" => "s503*part_503",
				"storage" => "E03_3.ks",
				"tag" => "s503",
				"target" => "*part_503",
				"type" => "section"
			],
			(const) %[
				"comment" => "青い性と誠意の両立",
				"id" => "s504*part_504",
				"storage" => "E04H.ks",
				"tag" => "s504",
				"target" => "*part_504",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_6_2",
				"name" => "CHAPTER 5",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "殺傷兵器？",
				"id" => "s506*part_506",
				"storage" => "E06_2.ks",
				"tag" => "s506",
				"target" => "*part_506",
				"type" => "section"
			],
			(const) %[
				"comment" => "あいえいちに気をつけて",
				"id" => "s506*chapter5-2_ori",
				"storage" => "E06_2.ks",
				"tag" => "s506",
				"target" => "*chapter5-2_ori",
				"type" => "section"
			],
			(const) %[
				"comment" => "お休み下手ガール",
				"id" => "s507*part_507",
				"storage" => "E07_3.ks",
				"tag" => "s507",
				"target" => "*part_507",
				"type" => "section"
			],
			(const) %[
				"comment" => "進化の話",
				"id" => "s507*chapter5-4_ori",
				"storage" => "E07_3.ks",
				"tag" => "s507",
				"target" => "*chapter5-4_ori",
				"type" => "section"
			],
			(const) %[
				"comment" => "潮の香りの去り際に",
				"id" => "s508*part_508",
				"storage" => "E08_3.ks",
				"tag" => "s508",
				"target" => "*part_508",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_6_3",
				"name" => "CHAPTER 6",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "私は、そういう女です",
				"id" => "s509*part_509",
				"storage" => "E09_2.ks",
				"tag" => "s509",
				"target" => "*part_509",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_6_4",
				"name" => "CHAPTER 7",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "偶然に感謝",
				"id" => "s519*part_519",
				"storage" => "E19.ks",
				"tag" => "s519",
				"target" => "*part_519",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_6_5",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s520*part_520",
				"storage" => "E20.ks",
				"tag" => "s520",
				"target" => "*part_520",
				"type" => "section"
			]
		],
		(const) [
			(const) %[
				"id" => "chapter_7_1",
				"name" => "CHAPTER 4",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "お中元？",
				"id" => "s601*part_601",
				"storage" => "【風実花】01（お土産）.ks",
				"tag" => "s601",
				"target" => "*part_601",
				"type" => "section"
			],
			(const) %[
				"comment" => "今年こそは！",
				"id" => "s603*part_603",
				"storage" => "【風実花】03（水着）.ks",
				"tag" => "s603",
				"target" => "*part_603",
				"type" => "section"
			],
			(const) %[
				"comment" => "魔王とファリ",
				"id" => "s604*part_604",
				"storage" => "【風実花】04（課外授業）.ks",
				"tag" => "s604",
				"target" => "*part_604",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_7_2",
				"name" => "CHAPTER 5",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "新たな事実",
				"id" => "s606*part_606",
				"storage" => "【風実花】06（しつこい男）.ks",
				"tag" => "s606",
				"target" => "*part_606",
				"type" => "section"
			],
			(const) %[
				"id" => "chapter_7_3",
				"name" => "EPILOGUE",
				"type" => "chapter"
			],
			(const) %[
				"comment" => "EPILOGUE",
				"id" => "s607*part_607",
				"storage" => "【風実花】07（END）.ks",
				"tag" => "s607",
				"target" => "*part_607",
				"type" => "section"
			]
		]
	],
	"routes" => (const) [
		"共通",
		"乃愛",
		"天音",
		"来海",
		"かぐ耶",
		"オリエ",
		"風実花"
	],
	"selects" => (const) [
		"s005*part_005_sel1",
		"s011*part_011_sel1",
		"s012*part_012_sel1",
		"s013*part_013_sel1",
		"s013*part_013_sel2",
		"s013*part_013_sel3",
		"s013*part_013_sel4"
	]
]
